test: adding commit message to assertion errors
## Problem
When an assertion fails it is hard to determine which commit message case caused the failing test for the non-generated tests.

**E.g.**

```
---- commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_18 stdout ----
-------------- TEST START --------------
thread 'commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_18' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[NonConventionalCommitsSpecification, PrecedingWhitespace]`', conventional_commits_linter_lib/src/commits/commit/tests/mod.rs:49:5
```

## Solution
Updating the non-generated tests assertion to include the commit message which is printed upon the assertion failing.
Producing a more readable assertion error, which highlights the exact commit message causing the failed test.

**E.g.**

```
---- commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_18 stdout ----
-------------- TEST START --------------
thread 'commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_18' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[NonConventionalCommitsSpecification, PrecedingWhitespace]`:

Failed the assertion upon the commit message:
" refactor(ts)!: ship yargs.d.ts (#1671)"

', conventional_commits_linter_lib/src/commits/commit/tests/mod.rs:49:5
```