test: test assertion on content
## Problem
If the `is_empty()` assertion fails no useful information is returned.

## Solution
Changing to assert the returned linting errors are equal to an empty array to get a better error message.

E.g.

```
failures:

---- commits::commit::tests::test_angular_type_conventional_commits::case_15 stdout ----
-------------- TEST START --------------
thread 'commits::commit::tests::test_angular_type_conventional_commits::case_15' panicked at 'assertion failed: linting_errors.is_empty()', conventional_commits_linter_lib/src/commits/commit/tests/mod.rs:48:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_15 stdout ----
-------------- TEST START --------------
thread 'commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_15' panicked at 'assertion failed: linting_errors.is_empty()', conventional_commits_linter_lib/src/commits/commit/tests/mod.rs:36:5

failures:
    commits::commit::tests::test_angular_type_conventional_commits::case_15
    commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_15
```

vs

```
failures:

---- commits::commit::tests::test_angular_type_conventional_commits::case_15 stdout ----
-------------- TEST START --------------
thread 'commits::commit::tests::test_angular_type_conventional_commits::case_15' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[NonConventionalCommitsSpecification]`', conventional_commits_linter_lib/src/commits/commit/tests/mod.rs:50:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_15 stdout ----
-------------- TEST START --------------
thread 'commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_15' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[NonConventionalCommitsSpecification]`', conventional_commits_linter_lib/src/commits/commit/tests/mod.rs:37:5

failures:
    commits::commit::tests::test_angular_type_conventional_commits::case_15
    commits::commit::tests::test_angular_type_conventional_commits_and_only_angular_type::case_15
```